//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObrazPlus.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MaterialDBEntities : DbContext
    {
        public MaterialDBEntities()
            : base("name=MaterialDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Material_products> Material_products { get; set; }
        public DbSet<Material_type> Material_type { get; set; }
        public DbSet<Materials> Materials { get; set; }
        public DbSet<Product_type> Product_type { get; set; }
        public DbSet<Products> Products { get; set; }
        public DbSet<StorageUnits> StorageUnits { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
