//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObrazPlus.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        public Materials()
        {
            this.Material_products = new HashSet<Material_products>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int MaterialTypeId { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal QuantityInStock { get; set; }
        public decimal MinQuantity { get; set; }
        public decimal QuantityInPackage { get; set; }
        public int StorageUnitsId { get; set; }
    
        public virtual ICollection<Material_products> Material_products { get; set; }
        public virtual Material_type Material_type { get; set; }
        public virtual StorageUnits StorageUnits { get; set; }
    }
}
