//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObrazPlus.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_type
    {
        public Material_type()
        {
            this.Materials = new HashSet<Materials>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public double LostPercent { get; set; }
    
        public virtual ICollection<Materials> Materials { get; set; }
    }
}
