//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObrazPlus.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.Material_products = new HashSet<Material_products>();
        }
    
        public int Id { get; set; }
        public int ProductTypeId { get; set; }
        public string Title { get; set; }
        public string Article { get; set; }
        public decimal MinCost { get; set; }
    
        public virtual ICollection<Material_products> Material_products { get; set; }
        public virtual Product_type Product_type { get; set; }
    }
}
